# Generated by Django 4.2 on 2023-04-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_payment_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='apartment_address',
            new_name='apartments_address',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
