# Generated by Django 4.2 on 2023-04-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_item_image2_item_image3_item_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
