# Generated by Django 4.2 on 2023-04-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_item_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='additional',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image4',
            field=models.ImageField(upload_to=''),
        ),
    ]
